Let's assume we have collected some interesting datasets and we want to make predictions and recomendations based on them. The datasets are simply CSV files.

There are multiple ways of working with CSV files in Python. We could just `open(file)` and parse its content manually

In [3]:
open('dataset/ratings.csv')

but that would be re-inventing the wheel, as there is already built-in `csv` module for that

In [4]:
import csv
reader = csv.reader(open('dataset/ratings.csv'))
next(reader)

['userId', 'movieId', 'rating', 'timestamp']

In [5]:
next(reader)

['1', '31', '2.5', '1260759144']

Much better, now you can just iterate through the dataset and do your analysis, although you still have to write that code yourself. We can do better with `pandas`, which provides comfortable data analysis API

In [6]:
import pandas

Let's start from importing our dataset

In [7]:
df = pandas.read_csv('dataset/ratings.csv')

`read_csv` function will load the csv from provided path and transform it into `DataFrame` object, which is the primary data structure used when working with Pandas

In [8]:
type(df)

pandas.core.frame.DataFrame

Whenever you want to quickly preview the result of your operations, simply print your `DataFrame`, it has a `__str__` method implemented which renders nicely formatted output. You can easily see all the columns and how many rows are returned.

In [9]:
df

        userId  movieId  rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
5            1     1263     2.0  1260759151
6            1     1287     2.0  1260759187
7            1     1293     2.0  1260759148
8            1     1339     3.5  1260759125
9            1     1343     2.0  1260759131
10           1     1371     2.5  1260759135
11           1     1405     1.0  1260759203
12           1     1953     4.0  1260759191
13           1     2105     4.0  1260759139
14           1     2150     3.0  1260759194
15           1     2193     2.0  1260759198
16           1     2294     2.0  1260759108
17           1     2455     2.5  1260759113
18           1     2968     1.0  1260759200
19           1     3671     3.0  1260759117
20           2       10     4.0   835355493
21           2       17     5.0   835355681
22           2       39     5.0   835355604
23           2       47     4.0   835355552
24           2       50     4.0   835355586
25           2       52     3.0   835356031
26           2       62     3.0   835355749
27           2      110     4.0   835355532
28           2      144     3.0   835356016
29           2      150     5.0   835355395
...        ...      ...     ...         ...
99974      671     4034     4.5  1064245493
99975      671     4306     5.0  1064245548
99976      671     4308     3.5  1065111985
99977      671     4880     4.0  1065111973
99978      671     4886     5.0  1064245488
99979      671     4896     5.0  1065111996
99980      671     4963     4.5  1065111855
99981      671     4973     4.5  1064245471
99982      671     4993     5.0  1064245483
99983      671     4995     4.0  1064891537
99984      671     5010     2.0  1066793004
99985      671     5218     2.0  1065111990
99986      671     5299     3.0  1065112004
99987      671     5349     4.0  1065111863
99988      671     5377     4.0  1064245557
99989      671     5445     4.5  1064891627
99990      671     5464     3.0  1064891549
99991      671     5669     4.0  1063502711
99992      671     5816     4.0  1065111963
99993      671     5902     3.5  1064245507
99994      671     5952     5.0  1063502716
99995      671     5989     4.0  1064890625
99996      671     5991     4.5  1064245387
99997      671     5995     4.0  1066793014
99998      671     6212     2.5  1065149436
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

Doing simple statistics is trivial

In [10]:
df.rating.mean()

3.5436082556697732

In [11]:
df.rating.max()

5.0

In [12]:
df.rating.min()

0.5

In [13]:
df.rating.std()

1.0580641091070389

The real power of Pandas comes with queries and aggregations

In [14]:
df.query('movieId==1')

       userId  movieId  rating   timestamp
495         7        1     3.0   851866703
699         9        1     4.0   938629179
889        13        1     5.0  1331380058
962        15        1     2.0   997938310
3105       19        1     3.0   855190091
3528       20        1     3.5  1238729767
4008       23        1     3.0  1148729853
4781       26        1     5.0  1360087980
5048       30        1     4.0   944943070
6625       37        1     4.0   981308121
7142       43        1     4.0   974768260
7252       44        1     4.0   858707138
7337       47        1     5.0   832228931
7375       48        1     4.0  1318796720
8222       55        1     3.0   855926941
8260       56        1     4.0  1467004817
9416       63        1     5.0  1079098216
9610       67        1     3.0   854711770
9713       68        1     4.0  1194741818
9836       69        1     5.0  1366831110
9917       70        1     5.0   853954235
10023      72        1     3.5  1461778737
10214      73        1     5.0  1303464840
11873      75        1     3.0  1165607201
12038      77        1     4.0  1163005363
12616      79        1     2.0  1182994648
13068      84        1     3.5  1429910800
13291      86        1     3.0   848161799
13481      87        1     3.0   858623186
13767      89        1     5.0  1257620018
...       ...      ...     ...         ...
86155     577        1     5.0  1111475159
86489     580        1     4.0  1155616380
87618     584        1     5.0  1276156510
87811     585        1     4.0   974607482
88111     586        1     4.0  1214234202
89089     594        1     4.0   938948878
89164     595        1     5.0   965077903
89327     596        1     3.5  1145034973
89814     597        1     5.0   940708550
90016     598        1     4.5  1057554797
90730     603        1     4.0   868354978
91361     607        1     4.5  1113319531
91788     608        1     4.0   939461651
92559     615        1     4.0  1425504992
92944     616        1     4.0   860572913
93431     623        1     4.5  1225256593
93534     624        1     5.0  1019126661
95801     630        1     4.0  1443807734
95970     636        1     3.0   855227186
96149     641        1     4.0   850021197
96418     646        1     5.0   953449518
96587     647        1     4.0   947292218
96993     649        1     4.0   834424768
97399     653        1     4.0   948160430
97450     654        1     5.0  1145390085
98531     660        1     2.5  1436680062
98714     663        1     4.0  1438397999
98740     664        1     3.5  1362421730
99858     670        1     4.0   938782344
99889     671        1     5.0  1064891129

[247 rows x 4 columns]

In [15]:
pandas.read_csv('dataset/movies.csv').query('movieId==1')

   movieId             title                                       genres
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy

The main goal of a recommender system is to show you other content you might also want to see. For example, when you are watching YouTube video, you are also seeing other videos. One of the approaches to implement such a functionality is to find similar movies based on user ratings.

User rates a movie in 1-5 scale, then we are trying to find other users who rated that movie similarly and what other movies they liked. Those movies might also be interesting to our user, if only he has not seen them before.

In [16]:
pivot_table = pandas.pivot_table(df, index='movieId', columns=['userId'], values='rating')
pivot_table

userId,1,2,3,4,5,6,7,8,9,10,...,662,663,664,665,666,667,668,669,670,671
movieId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,4.0,NaN,...,NaN,4.0,3.5,NaN,NaN,NaN,NaN,NaN,4.0,5.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.0,NaN,5.0,4.0,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,4.0,NaN,4.0,NaN,NaN,3.0,NaN,NaN,NaN,...,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.0,4.0,NaN,2.0,NaN,NaN,NaN,NaN
17,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,5.0,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160080,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162542,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

As you can see, our dataset is really sparse - meaning we have very little ratings filled in. Actually we can check the ratio of filled ratings to number of all user-movie pairs

In [17]:
df.size

400016

In [18]:
pivot_table.size

6083286

In [19]:
1 - (df.size / pivot_table.size)

0.93424343356534612

93% of user-movie pairs are not filled in, so it would be a huge waste of space to keep entire matrix memory.

We want to efficiently compute [Cosine Similarity](https://en.wikipedia.org/wiki/Cosine_similarity) between movies, so for a given movie we can find similar ones. We can use `sklearn` for that and its pairwise [cosine similarity](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.cosine_similarity.html), but first we will optimize our data structures a little bit using Sparse Column Matrix, as we have limited set of ratings for movies.

In [40]:
from scipy.sparse import csr_matrix

In order to use Sparse Column Matrix, we need to prepare our data in such a way, that it can passed in the constructor. Its arguments are `csc_matrix(data, (rows, columns))`. 

Each of the arguments is 1-dimensional array, so to initialize 1x1 matrix, we pass `csc_matrix([value], ([0], [0]))`.

Thanks to that we don't have to initialize entire huge matrix in memory first, we can use only the data we really need.

In [84]:
unique_movie_ids = df.movieId.unique()
unique_user_ids = df.userId.unique()

movieIdToIndexMap = dict(map(lambda iterable: [int(iterable[1]), iterable[0]], enumerate(unique_movie_ids)))
userIdToIndexMap = dict(map(lambda iterable: [int(iterable[1]), iterable[0]], enumerate(unique_user_ids)))

In [85]:
ratings = []
movieIdIndices = []
userIdIndices = []

for index, row in df.iterrows():
    ratings.append(row.rating)
    movieIdIndices.append(movieIdToIndexMap[int(row.movieId)])
    userIdIndices.append(userIdToIndexMap[int(row.userId)])

In [41]:
rows_num = len(df.movieId.unique())
cols_num = len(df.userId.unique())

In [48]:
matrix = csr_matrix((ratings, (movieIdIndices, userIdIndices)), shape=(rows_num, cols_num))

In [49]:
matrix

<9066x671 sparse matrix of type '<class 'numpy.float64'>'
	with 100004 stored elements in Compressed Sparse Row format>

In [50]:
matrix.toarray()

array([[ 2.5,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 3. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 3. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       ...,
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ]])

In [51]:
matrix[1, :]

<1x671 sparse matrix of type '<class 'numpy.float64'>'
	with 42 stored elements in Compressed Sparse Row format>

In [36]:
from sklearn.metrics.pairwise import cosine_similarity

Let's try to compare the movie with id=1 to itself, we would expect that similarity will be 100%

In [54]:
cosine_similarity(matrix[1, :], matrix[1, :])

array([[ 1.]])

And the result is as expected, now we can try more real example and compare with another movie, choosing totally different genres (horror vs children movie) should give us low similarity

In [56]:
pandas.read_csv('dataset/movies.csv').query('movieId==159858')

      movieId                   title  genres
9097   159858  The Conjuring 2 (2016)  Horror

In [57]:
pandas.read_csv('dataset/movies.csv').query('movieId==1')

   movieId             title                                       genres
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy

In [58]:
cosine_similarity(
    matrix[movieIdToIndexMap[159858], :],
    matrix[movieIdToIndexMap[1], :]
)

array([[ 0.07652809]])

Great! That's clearly low similary. Let's see if it gives expected results when movies are actually similar to each other, like 2 editions Jurassic Park

In [79]:
pandas.read_csv('dataset/movies.csv').query('movieId==480 | movieId==4638')

      movieId                     title                            genres
427       480      Jurassic Park (1993)  Action|Adventure|Sci-Fi|Thriller
3641     4638  Jurassic Park III (2001)  Action|Adventure|Sci-Fi|Thriller

In [87]:
cosine_similarity(
    matrix[movieIdToIndexMap[480], :],
    matrix[movieIdToIndexMap[4638], :]
)

array([[ 0.24505641]])

As you can see similary is higher, if we compared all movies to each other, we could create a similarity matrix, which would enable us to quickly search similar movies

In [117]:
selected_movie = matrix[movieIdToIndexMap[1], :]
similar_movies = [] 
for index, movie_id in enumerate(unique_movie_ids):
    similarity = cosine_similarity(
        selected_movie,
        matrix[index, :]
    )[0][0]
    similar_movies.append((movie_id, similarity))

In [118]:
similar_movies.sort(key=lambda x: x[1], reverse=True)

This is an intuitive way of computing similarities, but quite slow, it's better to just pass entire matrix to `cosine_similarity` matrix function and we will get the result much faster, moreover it will be computer for all movies at once.

In [122]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(matrix)

array([[ 1.        ,  0.10058858,  0.19164838, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.10058858,  1.        ,  0.17538512, ...,  0.16238844,
         0.16238844,  0.        ],
       [ 0.19164838,  0.17538512,  1.        , ...,  0.14400461,
         0.14400461,  0.        ],
       ...,
       [ 0.        ,  0.16238844,  0.14400461, ...,  1.        ,
         1.        ,  0.        ],
       [ 0.        ,  0.16238844,  0.14400461, ...,  1.        ,
         1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ]])

In [119]:
movies_db = pandas.read_csv('dataset/movies.csv', index_col='movieId')
for movie_id, similarity in similar_movies[:10]:
    print(movies_db.loc[movie_id].title, movies_db.loc[movie_id].genres, similarity)

Toy Story (1995) Adventure|Animation|Children|Comedy|Fantasy 1.0
Toy Story 2 (1999) Adventure|Animation|Children|Comedy|Fantasy 0.594709812032
Star Wars: Episode IV - A New Hope (1977) Action|Adventure|Sci-Fi 0.576187845977
Forrest Gump (1994) Comedy|Drama|Romance|War 0.564533861453
Independence Day (a.k.a. ID4) (1996) Action|Adventure|Sci-Fi|Thriller 0.56294560026
Groundhog Day (1993) Comedy|Fantasy|Romance 0.548023021399
Back to the Future (1985) Adventure|Comedy|Sci-Fi 0.536700289574
Jurassic Park (1993) Action|Adventure|Sci-Fi|Thriller 0.535197077837
Shrek (2001) Adventure|Animation|Children|Comedy|Fantasy|Romance 0.532685098741
Star Wars: Episode VI - Return of the Jedi (1983) Action|Adventure|Sci-Fi 0.529334044309